# Generated by Django 3.2 on 2024-11-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_batmen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batmen',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
