# Generated by Django 3.2 on 2024-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_batmen_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batmen',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
